### ISSUE TITLE
Issue - basic test as wiki says

### ISSUE THREAD

**Issue by glaucioguerra** [aristeuroriz/sentiment-ptbr#1]
Hi,
I tried to do the same test indicated by the wiki with no success. I executed the follow steps:

1. Create new npm project
2. npm install sentiment-ptbr
3. Copy the same sample code and exec: node teste.js
The output is:

C:\Users\glaucioguerra\node-red-test>node teste.js
{ score: 0,
  comparative: 0,
  tokens: [ 'gatos', 'são', 'estúpidos' ],
  words: [],
  positive: [],
  negative: [] }
{ score: 0,
  comparative: 0,
  tokens: [ 'gatos', 'são', 'incríveis' ],
  words: [],
  positive: [],
  negative: [] }

Any idea?

Thanks

**Comment by dicarvallho** [comment]
This wont work cause the the word list is incomplete.
the word 'incríveis' dont exist in the list, so u need to add yourself =/

**Comment by dicarvallho** [comment]
try this:
open the file build/affin.json, add this after '{' :
"incríveis": 3,
"incrível": 3,
"amo": 3,
"amei": 3,
"amou": 3,

then run the test again and it will work like a charm =]

**Comment by glaucioguerra** [comment]
Hi, thanks!
